/*
    MotorSpeed_param.c
    Generated by Gene-Auto toolset ver 2.4.10
    (launcher GALauncher)
    Generated on: 18/06/2015 17:11:52.864
    source model: MotorSpeed
    model version: 6.5
    last saved by:
    last saved on:
*/

/* Includes */

#include "MotorSpeed_param.h"

/* Variable definitions */

const volatile GAREAL b = 0.00012;
const volatile GAREAL l = 0.225;
const volatile GAREAL d = 0.000003;
