/*
    MotorSpeed.c
    Generated by Gene-Auto toolset ver 2.4.10
    (launcher GALauncher)
    Generated on: 18/06/2015 17:11:52.852
    source model: MotorSpeed
    model version: 6.5
    last saved by:
    last saved on:
*/

/* Includes */

#include "MotorSpeed.h"

/* Variable definitions */

/*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace4>  */
GAREAL U1_2;
/*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace1>  */
GAREAL U;
/*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace2>  */
GAREAL U2_2;
/*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace12>  */
GAREAL omg1_2;
/*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace11>  */
GAREAL omg2_2;
/*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace10>  */
GAREAL omg;
/*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace8>  */
GAREAL U3_2;
/*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace3>  */
GAREAL omg3_2;
GAUINT8 i1_m;

/* Function definitions */

void MotorSpeed_init() {
}

void MotorSpeed_compute(t_MotorSpeed_io *_io_) {
    /*  Output from <SystemBlock: name=MotorSpeed>/<SourceBlock: name=U1>/<OutDataPort: name=>  */
    GAREAL U1_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SourceBlock: name=U2>/<OutDataPort: name=>  */
    GAREAL U2_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SourceBlock: name=U3>/<OutDataPort: name=>  */
    GAREAL U3_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SourceBlock: name=U4>/<OutDataPort: name=>  */
    GAREAL U4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Mux>/<OutDataPort: name=>  */
    GAREAL Mux[4];
    /*  Output from <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Sqrt5>/<OutDataPort: name=>  */
    GAREAL omg1_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Sqrt6>/<OutDataPort: name=>  */
    GAREAL omg2_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Sqrt7>/<OutDataPort: name=>  */
    GAREAL omg3_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Sqrt8>/<OutDataPort: name=>  */
    GAREAL omg4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Add1>/<OutDataPort: name=>  */
    GAREAL Add1_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAUINT8 Constant1_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Relational\nOperator4>/<OutDataPort: name=>  */
    GABOOL Relational_Operator4_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Relational\nOperator5>/<OutDataPort: name=>  */
    GABOOL Relational_Operator5_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Switch5>/<OutDataPort: name=>  */
    GAREAL Switch5_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Add1>/<OutDataPort: name=>  */
    GAREAL Add1_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAUINT8 Constant1_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Relational\nOperator4>/<OutDataPort: name=>  */
    GABOOL Relational_Operator4_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Relational\nOperator5>/<OutDataPort: name=>  */
    GABOOL Relational_Operator5_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Switch5>/<OutDataPort: name=>  */
    GAREAL Switch5_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Add1>/<OutDataPort: name=>  */
    GAREAL Add1_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAUINT8 Constant1_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Relational\nOperator4>/<OutDataPort: name=>  */
    GABOOL Relational_Operator4_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Relational\nOperator5>/<OutDataPort: name=>  */
    GABOOL Relational_Operator5_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Switch5>/<OutDataPort: name=>  */
    GAREAL Switch5_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Add1>/<OutDataPort: name=>  */
    GAREAL Add1_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAUINT8 Constant1_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Relational\nOperator4>/<OutDataPort: name=>  */
    GABOOL Relational_Operator4_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Relational\nOperator5>/<OutDataPort: name=>  */
    GABOOL Relational_Operator5_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Switch5>/<OutDataPort: name=>  */
    GAREAL Switch5_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<CombinatorialBlock: name=1-c7^2+ld1>/<OutDataPort: name=>  */
    GAREAL omg1_7;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<CombinatorialBlock: name=Divide1>/<OutDataPort: name=>  */
    GAREAL Divide1_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<CombinatorialBlock: name=Divide2>/<OutDataPort: name=>  */
    GAREAL Divide2_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<CombinatorialBlock: name=Divide3>/<OutDataPort: name=>  */
    GAREAL Divide3_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld1>/<OutDataPort: name=>  */
    GAUINT8 ld1_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld2>/<OutDataPort: name=>  */
    GAUINT8 ld2_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld3>/<OutDataPort: name=>  */
    GAREAL ld3_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld4>/<OutDataPort: name=>  */
    GAREAL ld4_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld5>/<OutDataPort: name=>  */
    GAREAL ld5_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld6>/<OutDataPort: name=>  */
    GAUINT8 ld6_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<CombinatorialBlock: name=1-c7^2+ld1>/<OutDataPort: name=>  */
    GAREAL omg2_6;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<CombinatorialBlock: name=Divide1>/<OutDataPort: name=>  */
    GAREAL Divide1_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<CombinatorialBlock: name=Divide2>/<OutDataPort: name=>  */
    GAREAL Divide2_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<CombinatorialBlock: name=Divide3>/<OutDataPort: name=>  */
    GAREAL Divide3_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld1>/<OutDataPort: name=>  */
    GAUINT8 ld1_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld2>/<OutDataPort: name=>  */
    GAUINT8 ld2_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld3>/<OutDataPort: name=>  */
    GAREAL ld3_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld4>/<OutDataPort: name=>  */
    GAREAL ld4_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld5>/<OutDataPort: name=>  */
    GAREAL ld5_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld6>/<OutDataPort: name=>  */
    GAUINT8 ld6_1;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<CombinatorialBlock: name=1-c7^2+ld1>/<OutDataPort: name=>  */
    GAREAL omg3_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<CombinatorialBlock: name=Divide1>/<OutDataPort: name=>  */
    GAREAL Divide1_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<CombinatorialBlock: name=Divide2>/<OutDataPort: name=>  */
    GAREAL Divide2_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<CombinatorialBlock: name=Divide3>/<OutDataPort: name=>  */
    GAREAL Divide3_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld1>/<OutDataPort: name=>  */
    GAUINT8 ld1_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld2>/<OutDataPort: name=>  */
    GAUINT8 ld2_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld3>/<OutDataPort: name=>  */
    GAREAL ld3_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld4>/<OutDataPort: name=>  */
    GAREAL ld4_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld5>/<OutDataPort: name=>  */
    GAREAL ld5_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld6>/<OutDataPort: name=>  */
    GAUINT8 ld6_3;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<CombinatorialBlock: name=1-c7^2+ld1>/<OutDataPort: name=>  */
    GAREAL omg4_2;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<CombinatorialBlock: name=Divide1>/<OutDataPort: name=>  */
    GAREAL Divide1_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<CombinatorialBlock: name=Divide2>/<OutDataPort: name=>  */
    GAREAL Divide2_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<CombinatorialBlock: name=Divide3>/<OutDataPort: name=>  */
    GAREAL Divide3_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld1>/<OutDataPort: name=>  */
    GAUINT8 ld1_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld2>/<OutDataPort: name=>  */
    GAUINT8 ld2_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld3>/<OutDataPort: name=>  */
    GAREAL ld3_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld4>/<OutDataPort: name=>  */
    GAREAL ld4_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld5>/<OutDataPort: name=>  */
    GAREAL ld5_4;
    /*  Output from <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld6>/<OutDataPort: name=>  */
    GAUINT8 ld6_4;
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SourceBlock: name=U1>  */
    U1_1 = _io_->U1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SourceBlock: name=U1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld1>  */
    ld1_2 = 4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld1>  */
    ld1_1 = 4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld1>  */
    ld1_3 = 4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld1>  */
    ld1_4 = 4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld1>  */
    /*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace4>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace4>  */
    U1_2 = U1_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace4>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<SourceBlock: name=Constant>  */
    Constant_2 = 46595.5396;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<SourceBlock: name=Constant>  */
    Constant_1 = 46595.5396;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<SourceBlock: name=Constant>  */
    Constant_3 = 46595.5396;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<SourceBlock: name=Constant>  */
    Constant_4 = 46595.5396;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SourceBlock: name=U2>  */
    U2_1 = _io_->U2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SourceBlock: name=U2>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld2>  */
    ld2_2 = 2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld2>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld2>  */
    ld2_1 = 2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld2>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld2>  */
    ld2_3 = 2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld2>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld2>  */
    ld2_4 = 2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld2>  */
    /*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace1>  */
    U = U2_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<SourceBlock: name=Constant1>  */
    Constant1_2 = 0;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<SourceBlock: name=Constant1>  */
    Constant1_1 = 0;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<SourceBlock: name=Constant1>  */
    Constant1_3 = 0;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<SourceBlock: name=Constant1>  */
    Constant1_4 = 0;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld3>  */
    ld3_2 = b;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld3>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<CombinatorialBlock: name=Divide1>  */
    Divide1_2 = U1_1 / ld1_2 / ld3_2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<CombinatorialBlock: name=Divide1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld3>  */
    ld3_1 = b;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld3>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<CombinatorialBlock: name=Divide1>  */
    Divide1_1 = U1_1 / ld1_1 / ld3_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<CombinatorialBlock: name=Divide1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld3>  */
    ld3_3 = b;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld3>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<CombinatorialBlock: name=Divide1>  */
    Divide1_3 = U1_1 / ld1_3 / ld3_3;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<CombinatorialBlock: name=Divide1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld3>  */
    ld3_4 = b;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld3>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<CombinatorialBlock: name=Divide1>  */
    Divide1_4 = U1_1 / ld1_4 / ld3_4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<CombinatorialBlock: name=Divide1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SourceBlock: name=U3>  */
    U3_1 = _io_->U3;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SourceBlock: name=U3>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld4>  */
    ld4_2 = l;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld4>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<CombinatorialBlock: name=Divide2>  */
    Divide2_2 = U3_1 / ld2_2 / ld3_2 / ld4_2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<CombinatorialBlock: name=Divide2>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld4>  */
    ld4_1 = l;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld4>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<CombinatorialBlock: name=Divide2>  */
    Divide2_1 = U2_1 / ld2_1 / ld3_1 / ld4_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<CombinatorialBlock: name=Divide2>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld4>  */
    ld4_3 = l;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld4>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<CombinatorialBlock: name=Divide2>  */
    Divide2_3 = U3_1 / ld2_3 / ld3_3 / ld4_3;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<CombinatorialBlock: name=Divide2>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld4>  */
    ld4_4 = l;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld4>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<CombinatorialBlock: name=Divide2>  */
    Divide2_4 = U2_1 / ld2_4 / ld3_4 / ld4_4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<CombinatorialBlock: name=Divide2>  */
    /*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace2>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace2>  */
    U2_2 = U3_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace2>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld5>  */
    ld5_2 = d;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld5>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld5>  */
    ld5_1 = d;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld5>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld5>  */
    ld5_3 = d;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld5>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld5>  */
    ld5_4 = d;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld5>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld6>  */
    ld6_2 = 4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<SourceBlock: name=ld6>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld6>  */
    ld6_1 = 4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<SourceBlock: name=ld6>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld6>  */
    ld6_3 = 4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<SourceBlock: name=ld6>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld6>  */
    ld6_4 = 4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<SourceBlock: name=ld6>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SourceBlock: name=U4>  */
    U4 = _io_->U4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SourceBlock: name=U4>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<CombinatorialBlock: name=Divide3>  */
    Divide3_2 = U4 / ld6_2 / ld5_2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<CombinatorialBlock: name=Divide3>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<CombinatorialBlock: name=1-c7^2+ld1>  */
    omg1_7 = Divide1_2 - Divide2_2 - Divide3_2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function1>/<CombinatorialBlock: name=1-c7^2+ld1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Relational\nOperator4>  */
    Relational_Operator4_2 = omg1_7 > Constant_2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Relational\nOperator4>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Product>  */
    Product_2 = Relational_Operator4_2 * Constant_2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Relational\nOperator5>  */
    Relational_Operator5_2 = omg1_7 <= Constant1_2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Relational\nOperator5>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Add1>  */
    Add1_2 = Relational_Operator4_2 + Relational_Operator5_2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Add1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Product1>  */
    Product1_2 = Relational_Operator5_2 * Constant1_2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Add2>  */
    Add2_2 = Product_2 + Product1_2;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Switch5>  */
    if (Add1_2 != 0) {
        Switch5_2 = Add2_2;
    } else {
        Switch5_2 = omg1_7;
    }
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation1>/<CombinatorialBlock: name=Switch5>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Sqrt5>  */
    omg1_1 = sqrt(Switch5_2);
    /*  END Block: <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Sqrt5>  */
    /*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace12>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace12>  */
    omg1_2 = omg1_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace12>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<CombinatorialBlock: name=Divide3>  */
    Divide3_1 = U4 / ld6_1 / ld5_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<CombinatorialBlock: name=Divide3>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<CombinatorialBlock: name=1-c7^2+ld1>  */
    omg2_6 = Divide1_1 - Divide2_1 + Divide3_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function2>/<CombinatorialBlock: name=1-c7^2+ld1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Relational\nOperator4>  */
    Relational_Operator4_1 = omg2_6 > Constant_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Relational\nOperator4>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Product>  */
    Product_1 = Relational_Operator4_1 * Constant_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Relational\nOperator5>  */
    Relational_Operator5_1 = omg2_6 <= Constant1_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Relational\nOperator5>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Add1>  */
    Add1_1 = Relational_Operator4_1 + Relational_Operator5_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Add1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Product1>  */
    Product1_1 = Relational_Operator5_1 * Constant1_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Add2>  */
    Add2_1 = Product_1 + Product1_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Switch5>  */
    if (Add1_1 != 0) {
        Switch5_1 = Add2_1;
    } else {
        Switch5_1 = omg2_6;
    }
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation2>/<CombinatorialBlock: name=Switch5>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Sqrt6>  */
    omg2_1 = sqrt(Switch5_1);
    /*  END Block: <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Sqrt6>  */
    /*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace11>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace11>  */
    omg2_2 = omg2_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace11>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<CombinatorialBlock: name=Divide3>  */
    Divide3_3 = U4 / ld6_3 / ld5_3;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<CombinatorialBlock: name=Divide3>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<CombinatorialBlock: name=1-c7^2+ld1>  */
    omg3_3 = Divide1_3 + Divide2_3 - Divide3_3;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function3>/<CombinatorialBlock: name=1-c7^2+ld1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Relational\nOperator4>  */
    Relational_Operator4_3 = omg3_3 > Constant_3;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Relational\nOperator4>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Product>  */
    Product_3 = Relational_Operator4_3 * Constant_3;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Relational\nOperator5>  */
    Relational_Operator5_3 = omg3_3 <= Constant1_3;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Relational\nOperator5>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Add1>  */
    Add1_3 = Relational_Operator4_3 + Relational_Operator5_3;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Add1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Product1>  */
    Product1_3 = Relational_Operator5_3 * Constant1_3;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Add2>  */
    Add2_3 = Product_3 + Product1_3;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Switch5>  */
    if (Add1_3 != 0) {
        Switch5_3 = Add2_3;
    } else {
        Switch5_3 = omg3_3;
    }
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation3>/<CombinatorialBlock: name=Switch5>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Sqrt7>  */
    omg3_1 = sqrt(Switch5_3);
    /*  END Block: <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Sqrt7>  */
    /*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace10>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace10>  */
    omg = omg3_1;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace10>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<CombinatorialBlock: name=Divide3>  */
    Divide3_4 = U4 / ld6_4 / ld5_4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<CombinatorialBlock: name=Divide3>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<CombinatorialBlock: name=1-c7^2+ld1>  */
    omg4_2 = Divide1_4 + Divide2_4 + Divide3_4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Function8>/<CombinatorialBlock: name=1-c7^2+ld1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Relational\nOperator4>  */
    Relational_Operator4_4 = omg4_2 > Constant_4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Relational\nOperator4>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Product>  */
    Product_4 = Relational_Operator4_4 * Constant_4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Relational\nOperator5>  */
    Relational_Operator5_4 = omg4_2 <= Constant1_4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Relational\nOperator5>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Add1>  */
    Add1_4 = Relational_Operator4_4 + Relational_Operator5_4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Add1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Product1>  */
    Product1_4 = Relational_Operator5_4 * Constant1_4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Add2>  */
    Add2_4 = Product_4 + Product1_4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Switch5>  */
    if (Add1_4 != 0) {
        Switch5_4 = Add2_4;
    } else {
        Switch5_4 = omg4_2;
    }
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SystemBlock: name=Equiv_saturation4>/<CombinatorialBlock: name=Switch5>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Sqrt8>  */
    omg4 = sqrt(Switch5_4);
    /*  END Block: <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Sqrt8>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Mux>  */
    Mux[0] = omg1_1;
    Mux[1] = omg2_1;
    Mux[2] = omg3_1;
    Mux[3] = omg4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<CombinatorialBlock: name=Mux>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=omgs2>  */
    for (i1_m = 0; i1_m < 4; i1_m++) {
        _io_->omgs2[i1_m] = Mux[i1_m];
    }
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=omgs2>  */
    /*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace8>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace8>  */
    U3_2 = U4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace8>  */
    /*  Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace3>  */
    /*  START Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace3>  */
    omg3_2 = omg4;
    /*  END Block: <SystemBlock: name=MotorSpeed>/<SinkBlock: name=To Workspace3>  */
}

