/*
    Altitude.c
    Generated by Gene-Auto toolset ver 2.4.10
    (launcher GALauncher)
    Generated on: 22/06/2015 19:25:29.972
    source model: Altitude
    model version: 6.5
    last saved by:
    last saved on:
*/

/* Includes */

#include "Altitude.h"

/* Function definitions */

void Altitude_init(t_Altitude_state *_state_) {
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */

    _state_->Unit_Delay2_memory_1 = 0;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_2 = 0;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_3 = 0;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_4 = 0;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_1 = 0;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_2 = 0;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_3 = 0;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_4 = 0;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
}

void Altitude_compute(t_Altitude_io *_io_, t_Altitude_state *_state_) {
    /*  Output from <SystemBlock: name=Altitude>/<SourceBlock: name=z>/<OutDataPort: name=>  */
    GAREAL z;
    /*  Output from <SystemBlock: name=Altitude>/<SourceBlock: name=zd>/<OutDataPort: name=>  */
    GAREAL zd;
    /*  Output from <SystemBlock: name=Altitude>/<SourceBlock: name=phi>/<OutDataPort: name=>  */
    GAREAL phi_2;
    /*  Output from <SystemBlock: name=Altitude>/<SourceBlock: name=theta>/<OutDataPort: name=>  */
    GAREAL theta_2;
    /*  Output from <SystemBlock: name=Altitude>/<SourceBlock: name=dt>/<OutDataPort: name=>  */
    GAREAL dt;
    /*  Output from <SystemBlock: name=Altitude>/<CombinatorialBlock: name=Mux>/<OutDataPort: name=>  */
    GAREAL Mux_2[2];
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add_2;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Add1>/<OutDataPort: name=>  */
    GAREAL e8;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL phi_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL theta_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Mux>/<OutDataPort: name=>  */
    GAREAL Mux_1[3];
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Mux1>/<OutDataPort: name=>  */
    GAREAL Mux1[6];
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain5>/<OutDataPort: name=>  */
    GAREAL Gain5_2;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain6>/<OutDataPort: name=>  */
    GAREAL zddot;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL Sum1_2;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_2;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_2;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_2;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain5>/<OutDataPort: name=>  */
    GAREAL Gain5_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain6>/<OutDataPort: name=>  */
    GAREAL zddotdot;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL Sum1_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add_3;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain5>/<OutDataPort: name=>  */
    GAREAL Gain5_3;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain6>/<OutDataPort: name=>  */
    GAREAL Gain6;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum1>/<OutDataPort: name=>  */
    GAREAL Sum1_3;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add_4;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_3;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_3;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_3;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>/<OutDataPort: name=>  */
    GAREAL Add2;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>/<OutDataPort: name=>  */
    GAREAL Constant;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAREAL Constant1_2;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_4;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_2;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>/<OutDataPort: name=>  */
    GABOOL Relational_Operator4;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>/<OutDataPort: name=>  */
    GABOOL Relational_Operator5;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>/<OutDataPort: name=>  */
    GAREAL U1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL X4;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>/<OutDataPort: name=>  */
    GAREAL Product_5;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>/<OutDataPort: name=>  */
    GAREAL Unit_Delay1_4;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>/<OutDataPort: name=>  */
    GAREAL Unit_Delay2_4;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=1-c7^2+ld1>/<OutDataPort: name=>  */
    GAREAL _1_c7_2_ld1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=1-c7^2+ld4>/<OutDataPort: name=>  */
    GAREAL _1_c7_2_ld4;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_2;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_3;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_4;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_5;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>/<OutDataPort: name=>  */
    GAREAL Demux_6;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Divide>/<OutDataPort: name=>  */
    GAREAL Divide;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product1>/<OutDataPort: name=>  */
    GAREAL Product1_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product2>/<OutDataPort: name=>  */
    GAREAL Product2;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product3>/<OutDataPort: name=>  */
    GAREAL Product3;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Trigonometric\nFunction>/<OutDataPort: name=>  */
    GAREAL Trigonometric_Function;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Trigonometric\nFunction1>/<OutDataPort: name=>  */
    GAREAL Trigonometric_Function1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=c7+c8>/<OutDataPort: name=>  */
    GAREAL c7_c8;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=c7^2>/<OutDataPort: name=>  */
    GAREAL c7_2;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld1>/<OutDataPort: name=>  */
    GAUINT8 ld1_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld2>/<OutDataPort: name=>  */
    GAREAL ld2_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld3>/<OutDataPort: name=>  */
    GAREAL ld3_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld4>/<OutDataPort: name=>  */
    GAREAL ld4_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld5>/<OutDataPort: name=>  */
    GAREAL ld5_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld6>/<OutDataPort: name=>  */
    GAREAL ld6_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=u4*(1-c7^2+ld4)>/<OutDataPort: name=>  */
    GAREAL u4_1_c7_2_ld4_;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=u6*(c7+c8)>/<OutDataPort: name=>  */
    GAREAL u6_c7_c8_;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Add>/<OutDataPort: name=>  */
    GAREAL Add_5;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SourceBlock: name=Constant1>/<OutDataPort: name=>  */
    GAREAL Constant1_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SourceBlock: name=Constant2>/<OutDataPort: name=>  */
    GAREAL Constant2;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_2;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_1;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Demux1>/<OutDataPort: name=>  */
    GAREAL Demux1_3;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=c7*e7>/<OutDataPort: name=>  */
    GAREAL c7_e7;
    /*  Output from <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=ld4*X4>/<OutDataPort: name=>  */
    GAREAL ld4_X4;
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld1>  */
    ld1_1 = 1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>  */
    Constant = 22.36;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SourceBlock: name=z>  */
    z = _io_->z;
    /*  END Block: <SystemBlock: name=Altitude>/<SourceBlock: name=z>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SourceBlock: name=phi>  */
    phi_2 = _io_->phi;
    /*  END Block: <SystemBlock: name=Altitude>/<SourceBlock: name=phi>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_1 = _state_->Unit_Delay2_memory_1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_3 = _state_->Unit_Delay2_memory_2;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_2 = _state_->Unit_Delay2_memory_3;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    Unit_Delay2_4 = _state_->Unit_Delay2_memory_4;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SourceBlock: name=theta>  */
    theta_2 = _io_->theta;
    /*  END Block: <SystemBlock: name=Altitude>/<SourceBlock: name=theta>  */
    /*  START Block: <SystemBlock: name=Altitude>/<CombinatorialBlock: name=Mux>  */
    Mux_2[0] = phi_2;
    Mux_2[1] = theta_2;
    /*  END Block: <SystemBlock: name=Altitude>/<CombinatorialBlock: name=Mux>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Demux>  */
    phi_1 = Mux_2[0];
    theta_1 = Mux_2[1];
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant1>  */
    Constant1_2 = 0.01;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_2 = _state_->Unit_Delay1_memory_1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_1 = _state_->Unit_Delay1_memory_2;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_3 = _state_->Unit_Delay1_memory_3;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    Unit_Delay1_4 = _state_->Unit_Delay1_memory_4;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SourceBlock: name=zd>  */
    zd = _io_->zd;
    /*  END Block: <SystemBlock: name=Altitude>/<SourceBlock: name=zd>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SourceBlock: name=dt>  */
    dt = _io_->dt;
    /*  END Block: <SystemBlock: name=Altitude>/<SourceBlock: name=dt>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    Product_1 = dt * Unit_Delay2_1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    Product_3 = dt * Unit_Delay2_3;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    Product_2 = dt * Unit_Delay2_2;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    Product_5 = dt * Unit_Delay2_4;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    Add_1 = Product_2 + Unit_Delay1_2;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    Add_3 = Product_1 + Unit_Delay1_1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    Add_4 = Product_3 + Unit_Delay1_3;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum1>  */
    Sum1_3 = z - Add_4;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain6>  */
    Gain6 = (double) 1 / Tca3 * Sum1_3;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain6>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain5>  */
    Gain5_3 = (double) 1 / Tca3 * Sum1_3;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<CombinatorialBlock: name=Gain5>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    X4 = Product_5 + Unit_Delay1_4;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>  */
    Sum1_2 = zd - Add_1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain6>  */
    zddot = (double) 1 / Tca1 * Sum1_2;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain6>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain5>  */
    Gain5_2 = (double) 1 / Tca1 * Sum1_2;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<CombinatorialBlock: name=Gain5>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>  */
    Sum1_1 = zddot - Add_3;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Sum1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain6>  */
    zddotdot = (double) 1 / Tca2 * Sum1_1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain6>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain5>  */
    Gain5_1 = (double) 1 / Tca2 * Sum1_1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<CombinatorialBlock: name=Gain5>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld3>  */
    ld3_1 = ld4;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld3>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Add>  */
    Add_2 = zd - z;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SourceBlock: name=Constant1>  */
    Constant1_1 = c7;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SourceBlock: name=Constant1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld4>  */
    ld4_1 = c7;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld4>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=c7^2>  */
    c7_2 = ld4_1 * ld4_1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=c7^2>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=1-c7^2+ld4>  */
    _1_c7_2_ld4 = ld1_1 - c7_2 + ld3_1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=1-c7^2+ld4>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld5>  */
    ld5_1 = c8;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld5>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=c7+c8>  */
    c7_c8 = ld4_1 + ld5_1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=c7+c8>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SourceBlock: name=Constant2>  */
    Constant2 = ld4;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SourceBlock: name=Constant2>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld2>  */
    ld2_1 = 9.81;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld2>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld6>  */
    ld6_1 = m;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<SourceBlock: name=ld6>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Mux>  */
    Mux_1[0] = Add_2;
    Mux_1[1] = zddot;
    Mux_1[2] = X4;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Mux>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Demux1>  */
    Demux1_2 = Mux_1[0];
    Demux1_1 = Mux_1[1];
    Demux1_3 = Mux_1[2];
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Demux1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=c7*e7>  */
    c7_e7 = Demux1_2 * Constant1_1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=c7*e7>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=ld4*X4>  */
    ld4_X4 = Demux1_3 * Constant2;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=ld4*X4>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Add>  */
    Add_5 = Demux1_1 + ld4_X4 + c7_e7;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<CombinatorialBlock: name=Add>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SinkBlock: name=Scope>  */
    _state_->Scope_memory = Add_5;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=function>/<SinkBlock: name=Scope>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Add1>  */
    e8 = Add_5 - Gain6;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Add1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Mux1>  */
    Mux1[0] = phi_1;
    Mux1[1] = theta_1;
    Mux1[2] = zddotdot;
    Mux1[3] = Add_2;
    Mux1[4] = e8;
    Mux1[5] = X4;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<CombinatorialBlock: name=Mux1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>  */
    Demux_2 = Mux1[0];
    Demux_1 = Mux1[1];
    Demux_3 = Mux1[2];
    Demux_4 = Mux1[3];
    Demux_5 = Mux1[4];
    Demux_6 = Mux1[5];
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Demux>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Trigonometric\nFunction>  */
    Trigonometric_Function = cos(Demux_2);
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Trigonometric\nFunction>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Trigonometric\nFunction1>  */
    Trigonometric_Function1 = cos(Demux_1);
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Trigonometric\nFunction1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product1>  */
    Product1_1 = Trigonometric_Function * Trigonometric_Function1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=u4*(1-c7^2+ld4)>  */
    u4_1_c7_2_ld4_ = _1_c7_2_ld4 * Demux_4;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=u4*(1-c7^2+ld4)>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product2>  */
    Product2 = ld4_1 * ld3_1 * Demux_6;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product2>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=u6*(c7+c8)>  */
    u6_c7_c8_ = c7_c8 * Demux_5;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=u6*(c7+c8)>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=1-c7^2+ld1>  */
    _1_c7_2_ld1 = u4_1_c7_2_ld4_ + u6_c7_c8_ - Product2 + Demux_3 + ld2_1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=1-c7^2+ld1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product3>  */
    Product3 = ld6_1 * _1_c7_2_ld1;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Product3>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Divide>  */
    Divide = 1.0 / Product1_1 * Product3;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Subsystem>/<CombinatorialBlock: name=Divide>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>  */
    Relational_Operator4 = Divide > Constant;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator4>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>  */
    Product_4 = Relational_Operator4 * Constant;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>  */
    Relational_Operator5 = Divide < Constant1_2;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Relational\nOperator5>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>  */
    Product1_2 = Relational_Operator5 * Constant1_2;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Product1>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>  */
    Add2 = Product_4 + Product1_2;
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Add2>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>  */
    if (Add2 != 0) {
        U1 = Add2;
    } else {
        U1 = Divide;
    }
    /*  END Block: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_saturation>/<CombinatorialBlock: name=Switch5>  */
    /*  START Block: <SystemBlock: name=Altitude>/<SinkBlock: name=U1>  */
    _io_->U1 = U1;
    /*  END Block: <SystemBlock: name=Altitude>/<SinkBlock: name=U1>  */
    /*  START Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_4 = X4;
    /*  END Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_3 = Add_4;
    /*  END Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_2 = Add_3;
    /*  END Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    _state_->Unit_Delay1_memory_1 = Add_1;
    /*  END Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay1>  */
    /*  START Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_4 = Add_2;
    /*  END Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_3 = Gain5_2;
    /*  END Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn1>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_2 = Gain5_3;
    /*  END Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn3>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    /*  START Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
    _state_->Unit_Delay2_memory_1 = Gain5_1;
    /*  END Block memory write: <SystemBlock: name=Altitude>/<SystemBlock: name=ALTITUDE CONTROL\nIB1>/<SystemBlock: name=Equiv_TransferFn2>/<SystemBlock: name=Integrator >/<SequentialBlock: name=Unit Delay2>  */
}

